replicaCount: 2

image:
  repository: 905418303993.dkr.ecr.us-east-1.amazonaws.com/mtap-backend
  tag: v3
  pullPolicy: Always

serviceAccountName: ssm-reader
secretProviderClass: aws-ssm-provider
ssmSecretName: aws-ssm

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

namespace: development
host: dev.homelabs.me

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
tgb:
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:905418303993:targetgroup/mtap-dev-frontend/5e3080390aa35bdc

# ingress:
#   enabled: false
# className: alb
# annotations:
#   alb.ingress.kubernetes.io/scheme: internet-facing
#   alb.ingress.kubernetes.io/target-type: ip
#   alb.ingress.kubernetes.io/healthcheck-path: /
#   alb.ingress.kubernetes.io/healthcheck-port: "80"
#   alb.ingress.kubernetes.io/load-balancer-name: mtap-dev-ingress-alb
#   alb.ingress.kubernetes.io/use-existing-alb: "true"
#   # Explicitly tell controller not to manage security groups
#   alb.ingress.kubernetes.io/manage-backend-security-group-rules: "false"
#   # Skip creating listeners since they exist
#   alb.ingress.kubernetes.io/actions.skip-listener-creation: '{"enabled":"true"}'

service:
  type: ClusterIP
  port: 80
  targetPort: 80
