replicaCount: 2

image:
  repository: 484907490966.dkr.ecr.us-east-1.amazonaws.com/drupal
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

namespace: development
host: test.byklabs.store

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

ingress:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.redirect-to-https: |
      {"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT_ID:certificate/CERTIFICATE_ID

service:
  type: ClusterIP
  port: 80
  targetPort: 80
