# {{- if .Values.ingress.enabled -}}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-ingress
#   namespace: {{ .Values.namespace }}
#   annotations:
#     {{- toYaml .Values.ingress.annotations | nindent 4 }}
# spec:
#   ingressClassName: {{ .Values.ingress.className }}
#   rules:
#   - host: {{ .Values.host }}
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: {{ .Release.Name }}-service
#             port:
#               number: {{ .Values.service.port }}
# {{- end }}