apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass }}
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "mtap/dev/mysql"
        objectType: "secretsmanager"
        jmesPath:
          - path: MYSQL_DATABASE
            objectAlias: MYSQL_DATABASE
          - path: MYSQL_USERNAME
            objectAlias: MYSQL_USERNAME
          - path: MYSQL_PASSWORD
            objectAlias: MYSQL_PASSWORD
          - path: MYSQL_HOST
            objectAlias: MYSQL_HOST
          - path: MYSQL_PORT
            objectAlias: MYSQL_PORT
          - path: S3ACCESSKEY
            objectAlias: S3ACCESSKEY
          - path: S3SECRETKEY
            objectAlias: S3SECRETKEY
          - path: DRUPAL_ENV
            objectAlias: DRUPAL_ENV
  secretObjects:
  - secretName: {{ .Values.ssmSecretName }}
    type: Opaque
    data:
    - objectName: MYSQL_DATABASE
      key: MYSQL_DATABASE
    - objectName: MYSQL_USERNAME
      key: MYSQL_USERNAME
    - objectName: MYSQL_PASSWORD
      key: MYSQL_PASSWORD
    - objectName: MYSQL_HOST
      key: MYSQL_HOST
    - objectName: MYSQL_PORT
      key: MYSQL_PORT
    - objectName: S3ACCESSKEY
      key: S3ACCESSKEY
    - objectName: S3SECRETKEY
      key: S3SECRETKEY
    - objectName: DRUPAL_ENV
      key: DRUPAL_ENV
