apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass }}
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secretStore.objectName }}"
        objectType: "{{ .Values.secretStore.objectType }}"
        jmesPath:
          {{- range .Values.secretKeys }}
          - path: {{ . }}
            objectAlias: {{ . }}
          {{- end }}
  secretObjects:
    - secretName: {{ .Values.ssmSecretName }}
      type: Opaque
      data:
        {{- range .Values.secretKeys }}
        - objectName: {{ . }}
          key: {{ . }}
        {{- end }}